name: Lean

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lean:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Lean
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: Lean
      - run: lake build
